import { CARD_IMAGES } from './cardImages';

export interface TarotCard {
  name: string;
  nameEn: string;
  image: string;
  meaning: string;
}

export const TAROT_CARDS: TarotCard[] = [
  // 大阿尔卡纳 22 张
  { name: '愚者', nameEn: 'The Fool', image: CARD_IMAGES['愚者'], meaning: '开始、自由、纯真、冒险。' },
  { name: '魔术师', nameEn: 'The Magician', image: CARD_IMAGES['魔术师'], meaning: '创造力、行动、潜能、意志力。' },
  { name: '女祭司', nameEn: 'The High Priestess', image: CARD_IMAGES['女祭司'], meaning: '直觉、神秘、潜意识、智慧。' },
  { name: '女皇', nameEn: 'The Empress', image: CARD_IMAGES['女皇'], meaning: '丰饶、母性、自然、感官享受。' },
  { name: '皇帝', nameEn: 'The Emperor', image: CARD_IMAGES['皇帝'], meaning: '权威、结构、稳定、领导力。' },
  { name: '教皇', nameEn: 'The Hierophant', image: CARD_IMAGES['教皇'], meaning: '传统、信仰、教育、精神指引。' },
  { name: '恋人', nameEn: 'The Lovers', image: CARD_IMAGES['恋人'], meaning: '爱、和谐、关系、价值观。' },
  { name: '战车', nameEn: 'The Chariot', image: CARD_IMAGES['战车'], meaning: '意志、胜利、自律、控制。' },
  { name: '力量', nameEn: 'Strength', image: CARD_IMAGES['力量'], meaning: '勇气、耐心、内在力量、同情。' },
  { name: '隐士', nameEn: 'The Hermit', image: CARD_IMAGES['隐士'], meaning: '内省、寻求真理、孤独、指引。' },
  { name: '命运之轮', nameEn: 'Wheel of Fortune', image: CARD_IMAGES['命运之轮'], meaning: '运气、转折、轮回、不可控。' },
  { name: '正义', nameEn: 'Justice', image: CARD_IMAGES['正义'], meaning: '公平、真相、因果、平衡。' },
  { name: '倒吊人', nameEn: 'The Hanged Man', image: CARD_IMAGES['倒吊人'], meaning: '暂停、牺牲、新视角、放手。' },
  { name: '死亡', nameEn: 'Death', image: CARD_IMAGES['死亡'], meaning: '结束、转变、过渡、重生。' },
  { name: '节制', nameEn: 'Temperance', image: CARD_IMAGES['节制'], meaning: '平衡、节制、融合、耐心。' },
  { name: '恶魔', nameEn: 'The Devil', image: CARD_IMAGES['恶魔'], meaning: '束缚、成瘾、物质主义、诱惑。' },
  { name: '高塔', nameEn: 'The Tower', image: CARD_IMAGES['高塔'], meaning: '剧变、灾难、觉醒、解放。' },
  { name: '星星', nameEn: 'The Star', image: CARD_IMAGES['星星'], meaning: '希望、灵感、宁静、更新。' },
  { name: '月亮', nameEn: 'The Moon', image: CARD_IMAGES['月亮'], meaning: '不安、幻觉、直觉、波动。' },
  { name: '太阳', nameEn: 'The Sun', image: CARD_IMAGES['太阳'], meaning: '成功、快乐、活力、自信。' },
  { name: '审判', nameEn: 'Judgement', image: CARD_IMAGES['审判'], meaning: '重生、觉醒、决定、赦免。' },
  { name: '世界', nameEn: 'The World', image: CARD_IMAGES['世界'], meaning: '完成、达成、旅行、圆满。' },
  // 权杖 14 张
  { name: '权杖王牌', nameEn: 'Ace of Wands', image: CARD_IMAGES['权杖王牌'], meaning: '新开始、灵感、创造力、能量。' },
  { name: '权杖二', nameEn: 'Two of Wands', image: CARD_IMAGES['权杖二'], meaning: '规划、决策、视野、未来。' },
  { name: '权杖三', nameEn: 'Three of Wands', image: CARD_IMAGES['权杖三'], meaning: '远见、拓展、合作、等待成果。' },
  { name: '权杖四', nameEn: 'Four of Wands', image: CARD_IMAGES['权杖四'], meaning: '庆祝、稳定、家园、和谐。' },
  { name: '权杖五', nameEn: 'Five of Wands', image: CARD_IMAGES['权杖五'], meaning: '竞争、冲突、分歧、挑战。' },
  { name: '权杖六', nameEn: 'Six of Wands', image: CARD_IMAGES['权杖六'], meaning: '胜利、认可、自信、公众赞赏。' },
  { name: '权杖七', nameEn: 'Seven of Wands', image: CARD_IMAGES['权杖七'], meaning: '坚持、防御、立场、捍卫。' },
  { name: '权杖八', nameEn: 'Eight of Wands', image: CARD_IMAGES['权杖八'], meaning: '迅速、进展、消息、行动。' },
  { name: '权杖九', nameEn: 'Nine of Wands', image: CARD_IMAGES['权杖九'], meaning: '坚韧、警惕、边界、坚持。' },
  { name: '权杖十', nameEn: 'Ten of Wands', image: CARD_IMAGES['权杖十'], meaning: '负担、责任、压力、坚持。' },
  { name: '权杖侍从', nameEn: 'Page of Wands', image: CARD_IMAGES['权杖侍从'], meaning: '探索、热情、新消息、好奇。' },
  { name: '权杖骑士', nameEn: 'Knight of Wands', image: CARD_IMAGES['权杖骑士'], meaning: '冲动、冒险、热情、行动力。' },
  { name: '权杖王后', nameEn: 'Queen of Wands', image: CARD_IMAGES['权杖王后'], meaning: '自信、热情、独立、魅力。' },
  { name: '权杖国王', nameEn: 'King of Wands', image: CARD_IMAGES['权杖国王'], meaning: '领导、远见、企业家精神、魄力。' },
  // 星币 14 张
  { name: '星币王牌', nameEn: 'Ace of Pentacles', image: CARD_IMAGES['星币王牌'], meaning: '机会、富足、新开始、物质。' },
  { name: '星币二', nameEn: 'Two of Pentacles', image: CARD_IMAGES['星币二'], meaning: '平衡、多任务、适应、灵活。' },
  { name: '星币三', nameEn: 'Three of Pentacles', image: CARD_IMAGES['星币三'], meaning: '合作、技艺、团队、建造。' },
  { name: '星币四', nameEn: 'Four of Pentacles', image: CARD_IMAGES['星币四'], meaning: '稳定、保守、安全、控制。' },
  { name: '星币五', nameEn: 'Five of Pentacles', image: CARD_IMAGES['星币五'], meaning: '困难、匮乏、孤立、考验。' },
  { name: '星币六', nameEn: 'Six of Pentacles', image: CARD_IMAGES['星币六'], meaning: '给予、分享、公平、慈善。' },
  { name: '星币七', nameEn: 'Seven of Pentacles', image: CARD_IMAGES['星币七'], meaning: '耐心、投资、评估、等待。' },
  { name: '星币八', nameEn: 'Eight of Pentacles', image: CARD_IMAGES['星币八'], meaning: '技艺、专注、精进、工匠精神。' },
  { name: '星币九', nameEn: 'Nine of Pentacles', image: CARD_IMAGES['星币九'], meaning: '独立、富足、享受、自律。' },
  { name: '星币十', nameEn: 'Ten of Pentacles', image: CARD_IMAGES['星币十'], meaning: '传承、家族、长期安全、根基。' },
  { name: '星币侍从', nameEn: 'Page of Pentacles', image: CARD_IMAGES['星币侍从'], meaning: '学习、机会、勤奋、新计划。' },
  { name: '星币骑士', nameEn: 'Knight of Pentacles', image: CARD_IMAGES['星币骑士'], meaning: '踏实、可靠、耐心、按部就班。' },
  { name: '星币王后', nameEn: 'Queen of Pentacles', image: CARD_IMAGES['星币王后'], meaning: '滋养、务实、富足、关怀。' },
  { name: '星币国王', nameEn: 'King of Pentacles', image: CARD_IMAGES['星币国王'], meaning: '成功、财富、稳定、权威。' },
  // 圣杯 14 张
  { name: '圣杯王牌', nameEn: 'Ace of Cups', image: CARD_IMAGES['圣杯王牌'], meaning: '情感、爱、直觉、新关系。' },
  { name: '圣杯二', nameEn: 'Two of Cups', image: CARD_IMAGES['圣杯二'], meaning: '伙伴关系、和谐、联结、合作。' },
  { name: '圣杯三', nameEn: 'Three of Cups', image: CARD_IMAGES['圣杯三'], meaning: '庆祝、友谊、欢乐、团聚。' },
  { name: '圣杯四', nameEn: 'Four of Cups', image: CARD_IMAGES['圣杯四'], meaning: '内省、冷淡、选择、觉醒。' },
  { name: '圣杯五', nameEn: 'Five of Cups', image: CARD_IMAGES['圣杯五'], meaning: '失落、悲伤、放下、接受。' },
  { name: '圣杯六', nameEn: 'Six of Cups', image: CARD_IMAGES['圣杯六'], meaning: '回忆、怀旧、童年、单纯。' },
  { name: '圣杯七', nameEn: 'Seven of Cups', image: CARD_IMAGES['圣杯七'], meaning: '幻想、选择、梦想、幻觉。' },
  { name: '圣杯八', nameEn: 'Eight of Cups', image: CARD_IMAGES['圣杯八'], meaning: '离开、追寻、放下、内在探索。' },
  { name: '圣杯九', nameEn: 'Nine of Cups', image: CARD_IMAGES['圣杯九'], meaning: '满足、愿望达成、享受、感恩。' },
  { name: '圣杯十', nameEn: 'Ten of Cups', image: CARD_IMAGES['圣杯十'], meaning: '和谐、家庭、情感圆满、幸福。' },
  { name: '圣杯侍从', nameEn: 'Page of Cups', image: CARD_IMAGES['圣杯侍从'], meaning: '敏感、创意、直觉、新感受。' },
  { name: '圣杯骑士', nameEn: 'Knight of Cups', image: CARD_IMAGES['圣杯骑士'], meaning: '浪漫、邀请、理想主义、追求。' },
  { name: '圣杯王后', nameEn: 'Queen of Cups', image: CARD_IMAGES['圣杯王后'], meaning: '直觉、关怀、情感深度、包容。' },
  { name: '圣杯国王', nameEn: 'King of Cups', image: CARD_IMAGES['圣杯国王'], meaning: '情感成熟、平衡、包容、智慧。' },
  // 宝剑 14 张
  { name: '宝剑王牌', nameEn: 'Ace of Swords', image: CARD_IMAGES['宝剑王牌'], meaning: '突破、真相、清晰、新想法。' },
  { name: '宝剑二', nameEn: 'Two of Swords', image: CARD_IMAGES['宝剑二'], meaning: '两难、僵局、抉择、回避。' },
  { name: '宝剑三', nameEn: 'Three of Swords', image: CARD_IMAGES['宝剑三'], meaning: '心痛、失落、悲伤、疗愈。' },
  { name: '宝剑四', nameEn: 'Four of Swords', image: CARD_IMAGES['宝剑四'], meaning: '休息、恢复、沉思、暂停。' },
  { name: '宝剑五', nameEn: 'Five of Swords', image: CARD_IMAGES['宝剑五'], meaning: '冲突、胜负、争执、代价。' },
  { name: '宝剑六', nameEn: 'Six of Swords', image: CARD_IMAGES['宝剑六'], meaning: '过渡、离开、平静、前行。' },
  { name: '宝剑七', nameEn: 'Seven of Swords', image: CARD_IMAGES['宝剑七'], meaning: '策略、回避、独行、谨慎。' },
  { name: '宝剑八', nameEn: 'Eight of Swords', image: CARD_IMAGES['宝剑八'], meaning: '限制、恐惧、自我设限、觉醒。' },
  { name: '宝剑九', nameEn: 'Nine of Swords', image: CARD_IMAGES['宝剑九'], meaning: '焦虑、噩梦、担忧、释放。' },
  { name: '宝剑十', nameEn: 'Ten of Swords', image: CARD_IMAGES['宝剑十'], meaning: '结束、低谷、放手、黎明。' },
  { name: '宝剑侍从', nameEn: 'Page of Swords', image: CARD_IMAGES['宝剑侍从'], meaning: '好奇、消息、警觉、新想法。' },
  { name: '宝剑骑士', nameEn: 'Knight of Swords', image: CARD_IMAGES['宝剑骑士'], meaning: '果断、冲动、行动、挑战。' },
  { name: '宝剑王后', nameEn: 'Queen of Swords', image: CARD_IMAGES['宝剑王后'], meaning: '独立、清晰、诚实、洞察。' },
  { name: '宝剑国王', nameEn: 'King of Swords', image: CARD_IMAGES['宝剑国王'], meaning: '权威、理智、公正、决断。' },
];
